package com.core.match.msgs;

import com.core.connector.CommandSender;

/**
 * User: jgreco
 * THIS FILE IS AUTOGENERATED
 */
public interface MatchCommandSender extends CommandSender, MatchContributorListener {
    boolean send(MatchCommonCommand command);
    void add(MatchCommonCommand command);
}
