package com.core.match.itch.msgs;

/**
 * User: jgreco
 * THIS FILE IS AUTOGENERATED
 */
public class ITCHTestDispatcher extends ITCHBaseDispatcher {
    public boolean dispatch(ITCHCommonCommand msg1) {
        ITCHCommonEvent msg = (ITCHCommonEvent)msg1;
        switch (msg.getMsgType()) {
            case 'S':
                return dispatchITCHSystem((ITCHSystemEvent)msg);
            case 'R':
                return dispatchITCHSecurity((ITCHSecurityEvent)msg);
            case 'A':
                return dispatchITCHOrder((ITCHOrderEvent)msg);
            case 'X':
                return dispatchITCHOrderCancel((ITCHOrderCancelEvent)msg);
            case 'E':
                return dispatchITCHOrderExecuted((ITCHOrderExecutedEvent)msg);
            case 'P':
                return dispatchITCHTrade((ITCHTradeEvent)msg);
            default:
                return false;
        }
    }

    public void setLastTimestamp(long timestamp) {
        this.lastTimestamp = timestamp; 
    }
}

