package com.core.app;

/**
 * User: jgreco
 */
public class CommandException extends RuntimeException {
    /**
	 * generated by eclipse
	 */
	private static final long serialVersionUID = 4646195149447959369L;

	public CommandException(String ex) {
        super(ex);
    }

    public CommandException(Throwable ex) {
        super(ex);
    }
}
