package com.core.match.drops.gui.msgs;

import com.core.match.drops.DropVersionable;
import com.core.match.drops.gui.GUIUtils;

import java.nio.ByteBuffer; 

/* THIS FILE IS AUTOGENERATED */
public class GUIAccountRiskValues implements DropVersionable {
    private static final byte[] TYPE_BYTES = "\"type\":".getBytes();  
    private static final byte[] ACCOUNT_BYTES = ",\"account\":".getBytes();
    private static final byte[] TRADEEXPOSURE_BYTES = ",\"tradeExposure\":".getBytes();
    private static final byte[] ORDEREXPOSURE_BYTES = ",\"orderExposure\":".getBytes();
    private static final byte[] GROSSACTIVITY_BYTES = ",\"grossActivity\":".getBytes();
    private static final byte[] SES_BYTES = ",\"ses\":".getBytes();
    private static final byte[] CONTRIB_BYTES = ",\"contrib\":".getBytes();
    private static final byte[] ID_BYTES = ",\"id\":".getBytes();
    private static final byte[] VER_BYTES = ",\"ver\":".getBytes();
    private static final byte[] TIME_BYTES = ",\"time\":".getBytes();

    private final String account; 
	private long tradeExposure;
	private long orderExposure;
	private long grossActivity;
    private final int id; 
	private int ver;
	private long time;

    public GUIAccountRiskValues(
		int id
        , String account
		) {
        this.account = account;
        this.id = id;
    }

	public void write(ByteBuffer buffer, String ses, String contrib) {
		GUIUtils.startObject(buffer);
		GUIUtils.writeString(buffer, TYPE_BYTES, getType());		
		GUIUtils.writeString(buffer, ACCOUNT_BYTES, getAccount());		
		GUIUtils.writeLong(buffer, TRADEEXPOSURE_BYTES, getTradeExposure());		
		GUIUtils.writeLong(buffer, ORDEREXPOSURE_BYTES, getOrderExposure());		
		GUIUtils.writeLong(buffer, GROSSACTIVITY_BYTES, getGrossActivity());		
		GUIUtils.writeString(buffer, SES_BYTES, ses);
		GUIUtils.writeString(buffer, CONTRIB_BYTES, contrib);
		GUIUtils.writeInt(buffer, ID_BYTES, getId());		
		GUIUtils.writeInt(buffer, VER_BYTES, getVer());		
		GUIUtils.writeTime(buffer, TIME_BYTES, getTime());		
		GUIUtils.endObject(buffer);
    }
  
    public String getAccount() {
        return account;
    }
  
    public long getTradeExposure() {
        return tradeExposure;
    }
  
    public long getOrderExposure() {
        return orderExposure;
    }
  
    public long getGrossActivity() {
        return grossActivity;
    }
  
    public int getId() {
        return id;
    }
  
    public int getVer() {
        return ver;
    }
  
    public long getTime() {
        return time;
    }

	public void setTradeExposure(long val) {
		this.tradeExposure = val;
	}

	public void setOrderExposure(long val) {
		this.orderExposure = val;
	}

	public void setGrossActivity(long val) {
		this.grossActivity = val;
	}

	public void setVer(int val) {
		this.ver = val;
	}

	public void setTime(long val) {
		this.time = val;
	}
	
	public String getType() {
		return "accountRiskValues";
	}
} 
